window.brandModels = {
  "361°": ["Spire","Spire 6","Fury","Fury 4","Strata","Strata 4","Flame","Flame 9","Meraki","Meraki 3","Sensation","Sensation 5","Fierce"],
  "adidas": ["Adizero Adios Pro","Adizero Boston","Adizero Takumi Sen","Supernova","Supernova Rise","Ultraboost Light","Ultraboost 5","Solar Glide","Solar Boost","Terrex Agravic","Terrex Speed Ultra","Adizero Prime X","Adizero SL","Response Super"],
  "Allbirds": ["Tree Dasher","Tree Dasher 2","Tree Flyer","Tree Flyer 2","Trail Runner SWT","Tree Dashers Relay","Wool Dasher Mizzle","Natural Run Free","Tree Mill"],
  "Altra": ["Escalante","Escalante 4","Torin","Torin 7","Lone Peak","Lone Peak 8","Paradigm","Paradigm 7","Provision","Provision 7","Rivera","Rivera 3","Olympus","Timp","Via Olympus","FWD Experience"],
  "ASICS": ["Novablast","Novablast 4","Gel-Kayano","Gel-Kayano 31","Gel-Nimbus","Gel-Nimbus 26","Gel-Cumulus","Gel-Cumulus 26","Metaspeed Sky","Metaspeed Sky+","Metaspeed Edge","Gel-Superion","Gel-DS Trainer","GT-2000","GT-4000","Gel-Pulse","Gel-Contend","Gel-Venture","Trabuco Max","Fuji Lite"],
  "Atreyu": ["Base Model","Artist","Race Model","Daily Trainer","The Racer"],
  "Brooks": ["Ghost","Ghost 16","Glycerin","Glycerin 21","Glycerin GTS","Adrenaline GTS","Adrenaline GTS 24","Launch","Launch 11","Hyperion","Hyperion Max","Levitate","Revel","Trace","Caldera","Cascadia","Divide","Catamount"],
  "Craft": ["CTM Ultra","CTM Ultra Carbon","Pro Endur","Nordlite","Pro Endur Lace","Pro Pulse 2","CTM Ultra 2"],
  "Decathlon Kiprun": ["KD900","KD900X","KS900","KS900 Light","Ultralight","Race Light","KS500","KD500"],
  "Diadora": ["Mythos Blushield","Equilibrium","Elite Volo","Mythos Blushield Fly 4","Passo","Freccia"],
  "Hoka": ["Clifton","Clifton 9","Bondi","Bondi 8","Bondi SR","Mach","Mach 6","Rincon","Rincon 3","Arahi","Arahi 7","Carbon X","Carbon X 3","Speedgoat","Speedgoat 6","Challenger","Torrent","Zinal","Tecton X","Kawana","Solimar","Gaviota","Skyward X"],
  "Inov-8": ["Roadfly","Roadfly 375","Trailfly","Trailfly Ultra G 300","Trailfly G 270","Roclite","Roclite G 275","Mudtalon","X-Talon","X-Talon 255","Trailroc","Parkclaw","Rocfly"],
  "Joe Nimble": ["Addict","Trail Addict","Ultreya","WanderToes","TaoDactyls","BalanceToes"],
  "Karhu": ["Fusion","Fusion 3.5","Ikoni","Ikoni Evo","Synchron","Flow Trail"],
  "La Sportiva": ["Jackal","Jackal II","Akasha","Akasha II","Karacal","Mutant","Kaptiva","Bushido","Lycan","Cyklon","Prodigio","Akyra"],
  "Lems": ["Primal","Primal 2","Primal Zen","Trailhead","Mesa","Trailhead V2","Pursuit"],
  "Merrell": ["Vapor Glove","Vapor Glove 6","Trail Glove","Trail Glove 7","Agility Peak","Agility Peak 5","Long Sky","Long Sky 2","Morphlite","Fly Strike","Nova 3","Antora","MTL Skyfire"],
  "Mizuno": ["Wave Rider","Wave Rider 27","Wave Inspire","Wave Inspire 20","Wave Rebellion","Wave Rebellion Pro","Wave Sky","Wave Sky 7","Wave Horizon","Wave Creation","Wave Equate","Wave Prophecy","Wave Aero","Wave Duel"],
  "New Balance": ["Fresh Foam 1080","Fresh Foam 1080v13","FuelCell Rebel","FuelCell Rebel v4","Fresh Foam X 880","Fresh Foam X 880v13","Fresh Foam More","Fresh Foam More v4","RC Elite","RC Elite v3","FuelCell SuperComp Elite","FuelCell SC Trainer","FuelCell Propel","Fresh Foam X 860","Fresh Foam X Vongo","FuelCell Tempo","Nitrel"],
  "Newton": ["Gravity","Gravity 13","Distance","Distance S","Motion","Motion 14","Fate","Fate 3","Kismet","Boco AT"],
  "Nike": ["Pegasus","Pegasus 41","ZoomX Vaporfly","ZoomX Vaporfly Next% 3","Alphafly","Alphafly 3","Infinity Run","Infinity Run 4","Structure","Air Zoom Structure 25","React Infinity Run","Wildhorse","Terra Kiger","Zoomfly","Air Zoom Tempo","Invincible Run","Free RN","Zoom Fly","Streakfly"],
  "Norda": ["001","001 G+","002","003","Trail 001"],
  "NNormal": ["Kjerag","Tomir","Tomir 2","Kboix","Kboix 2"],
  "On": ["Cloudsurfer","Cloudsurfer 7","Cloudmonster","Cloudmonster 2","Cloudflow","Cloudflow 4","Cloudstratus","Cloudstratus 4","Cloudboom Echo","Cloudboom Strike","Cloudboom Echo 3","Cloudrunner","Cloudgo","Cloud 5","Cloudultra","Cloudultra 2","Cloudhorizon","Cloudventure","Cloudaway"],
  "Pearl Izumi": ["Flow","Fuel Cell","Trail N2","Road N1","X-Alp Summit","Pusuit","Flash","Project Cloud"],
  "PUMA": ["Deviate Nitro","Deviate Nitro 2","Deviate Nitro Elite","Velocity Nitro","Velocity Nitro 3","Magnify Nitro","Magnify Nitro 2","Eternity Nitro","Liberate Nitro","ForeverRun Nitro","Fast-R Nitro Elite"],
  "Reebok": ["Floatride Energy","Floatride Energy 5","Floatride Run Fast","Forever Floatride Grow","Nano X","Speed 22 TR","Floatride Energy Symmetros"],
  "Salomon": ["S/Lab Pulsar","S/Lab Pulsar SG","Sense Ride","Sense Ride 5","Ultra Glide","Ultra Glide 2","Speedcross","Speedcross 6","Supercross","Pulsar Trail","Genesis","Aero Glide","S/Lab Genesis"],
  "Saucony": ["Ride","Ride 17","Endorphin Speed","Endorphin Speed 4","Endorphin Pro","Endorphin Pro 4","Kinvara","Kinvara 15","Triumph","Triumph 21","Guide","Guide 17","Tempus","Peregrine","Peregrine 14","Axon","Cohesion","Everun Echelon","Endorphin Shift","Xodus Ultra"],
  "Skechers": ["GOrun Ride","GOrun Ride 10","GOrun Razor","GOrun Razor 4","MaxRoad","MaxRoad 6","GOrun Speed Elite","GOrun Pulse","GOrun Elevate","GOrun Pure 4","Arch Fit Road Walker"],
  "Topo Athletic": ["Ultrafly","Ultrafly 5","Phantom","Phantom 3","Fly Lite","Cyclone","Specter","Mtn Racer","Runventure","ST-5","Fli-Lyte"],
  "Under Armour": ["HOVR Machina","HOVR Machina 3","HOVR Infinite","HOVR Infinite 6","Charged Assert","Charged Pursuit","Charged Rogue","Charged Breeze","SlipSpeed","HOVR Sonic","HOVR Apex","Velociti Wind"],
  "Vibram FiveFingers": ["V-Run","V-Run 2","V-Trail","V-Trail 2","V-Alpha","KSO EVO","V-Trek","V-Neop","Bikila EVO","Lontra","Spyridon MR","EL-X"],
  "Vivobarefoot": ["Primus Lite","Primus Lite III","Primus Trail","Primus Trail III","Geo Racer","Stealth","Addis","Magna Trail","Magna FG","Tracker Forest ESG","Primus Trail Knit FG","Motus Strength","Magna SG"],
  "Xero Shoes": ["HFS","HFS II","Prio","Prio Neo","Speed Force","Mesa Trail","Mesa Trail II","Zelen","Forza Runner","Scrambler","Aqua Cloud","Xcursion Fusion","TerraFlex"],

  // --- Brands added/expanded ---
  "Asahi": ["Haze","Cloud Max","Flow Lite","Boost Pro"],
  "Birdies": ["The Sneaker","Starling Run","The Flat"],
  "Ciele Athletics": ["GOCap","FSTCap","Running Apparel"],
  "Columbia": ["Montrail F.K.T.","Montrail Trinity AG","Montrail Trinity MX","Peakfreak II OutDry","Escape Pursuit"],
  "Danner": ["Trail 2650","TrailTrek","Mountain 600","Cloud Cap"],
  "Dynafit": ["Alpine DNA","Feline SL","Ultra 100","Sky Pro","Alpine Pro","Radical Pro"],
  "Fila": ["Memory Speedstride","Memory Workshift","Evergrand","Headway 7"],
  "Goodr": ["OGs","BFGs","PHGs","Wrap Gs"],
  "Hilly": ["Cushion Socks","Twin Skin","Mono Skin"],
  "icebug": ["Acceleritas OCR","Acceleritas 8","Pytho5 Bugrip","Mist RB9X","Pytho BUGrip GTX","Arcus RB9X","Zeal BUGrip","Horizon BUGrip"],
  "Imperial Motion": ["Lux Trainer","Ridge Runner","Vapor"],
  "Jack Wolfskin": ["Terraventure 3","Thunder Hike","Prelight Pro","Vili Texapore Low","Cyrox Texapore"],
  "Karrimor": ["D30 Run","Mount Trail","Excel Run"],
  "Kalenji": ["Kiprun KS500","Kiprun KS900","Kiprun KD900","Elio Feel 900"],
  "Kswiss": ["Blade-Light Run","Kwicky Blade-Light","X Lite II"],
  "Lowa": ["Innox Evo GTX","Renegade GTX","Aerox GTX","Fortux GTX"],
  "Mammut": ["Sertig II Low GTX","Saentis Pro IS","Ducan Low GTX","Convey Low GTX","Aegility Pro Mid GTX"],
  "Montrail": ["F.K.T.","Trinity AG","Bajada IV","Trans Alps F.K.T."],
  "Naked": ["Barely There","Ultra High","Race"],
  "Nat's Feet": ["Trail Runner","Road Racer"],
  "Nathan": ["VaporAir","Pinnacle","QuickStart"],
  "Newline": ["Base","Runner","Race"],
  "Nike ACG": ["Mountain Fly","Air Nasu 2 GTX","Lowcate","Wildwood GTX"],
  "Oboz": ["Arete Low BDry","Sawtooth X Low BDry","Katabatic Mid BDry","Cirque Low B-Dry","Bridger Mid BDry"],
  "Patagonia": ["Lone Peak 5","Forerunner 2","Flintridge Rock Grip","Dirt Craft"],
  "Phoebe Street": ["Daily Trainer","Race Model"],
  "Polar": ["Pacer","Pacer Pro","Grit X"],
  "Raidlight": ["Revolutiv 3","Responsiv Ultra","Revolutiv 4","Activ Cushion"],
  "Ryka": ["Hydro Sport","Devotion Plus","Sky Walk","Influence"],
  "Scarpa": ["Ribelle Run XT GTX","Ribelle Run","Spin Ultra","Cyclone 2","Spin RS"],
  "Scott": ["Kinabalu RC","Supertrac RC","Supertrac Ultra RC","Speed Assault","Pursuit RC","Speed Elite","Kinabalu Power GTX"],
  "Sole": ["Motive","Motive Low","Scout OG","Scout Sport OG"],
  "Sorel": ["Kinetic Impact","Kinetic Breakthru","Kinetic Lite Lace","Explorer Lite"],
  "Speedo": ["Biofuse","Mariner","Aqua Skool"],
  "Strava": ["Sponsored Athletes"],
  "Suunto": ["Vertical","Vertical Titanium","Race"],
  "Swiss-X": ["Swiss-X Trail","Swiss-X Road","Swiss-X Carbon"],
  "Tecnica": ["Origin X LD","Sulfur GTX","Magma S","Inferno X Lite 3","Plasma S"],
  "The North Face": ["Summit Vectiv Pro","Vectiv Enduris","Vectiv Exploris","Flight Vectiv","VECTIV Taraval","Ultra 110 GTX","Activist Futurelight"],
  "Timberland": ["Garrison Trail Low WP","Trail Trekker Low GTX","Crossmark GTX","World Hiker"],
  "Topo Athletic": ["Ultrafly","Phantom","Fly Lite","Cyclone","Specter","Mtn Racer","Runventure","ST-5","Fli-Lyte"],
  "Torque": ["Trail Blazer","Road Warrior","Speed Demon"],
  "Trailroc": ["235","245","G 250"],
  "True Motion": ["U-Tech Nevos","U-Tech Nevos Element","O2 Feel"],
  "VJ Shoes": ["Ultra","Spark","MAXx","IROCK 3","Xero"],
  "Walsh": ["PB Elite","Fell Challenger","XTR","Burner"],
  "Wegelin": ["Trail Runner","Road Master"],
  "Wildcraft": ["Grit 2.0","Cliff Hanger","Trail Blast"],
  "Zamberlan": ["Trail Lite Low GTX RR","FreeBlast Low GTX RR","Hike H40","Crosser GTX RR","Nuuk GTX RR"]
};
